fix($MessageCreate): use `componentUtils` instead of `clientUtils`
This fixes the error `TypeError: this.clientUtils.commandMention is not a function` when someone mentions the bot.